name: Docker HTML Deployment

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print System Info
        run: uname -a

      - name: List Files
        run: ls -alh

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          
      - name: Verify Docker Installation
        run: docker --version

      - name: Create a Simple HTML Page
        run: |
          mkdir -p html
          echo '<!DOCTYPE html>
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Hello from Docker!</h1></body>
          </html>' > html/index.html

      - name: Create Dockerfile
        run: |
          echo 'FROM nginx:alpine
          COPY html /usr/share/nginx/html
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]' > Dockerfile

      - name: Build Docker Image
        run: docker build -t my-html-site:latest .

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name html-container my-html-site:latest

      - name: Verify Running Container
        run: docker ps -a
